import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const keywords = [
  "Archana",
  "AstroArt",
  "Archana AstroArt",
  "Astro Art",
  "Archana's Astrology",
  "Astrology Art",
  "Archana Astro",
  "AstroArchana",
  "Astrology Branding",
  "Astrology Themes",
  "Astrology",
  "Horoscope",
  "Zodiac",
  "Astro",
  "Stars and Planets",
  "Astrological Themes",
  "Astro Designs",
  "Astro Branding",
  "Spiritual Astrology",
  "Cosmic Art",
  "Personal Branding",
  "Archana Brand",
  "Astrology Personal Brand",
  "Astro Personal Branding",
  "Astrology Marketing",
  "AstroArt Branding",
  "AstroArt Campaign",
  "Astrology Blog",
  "Spiritual Blogging",
  "AstroArt Content",
  "Creative Astrology",
  "Astrology Art",
  "Spiritual Art",
  "Cosmic Designs",
  "Astrology Graphics",
  "Astro Creativity",
  "Astro Artworks",
  "Cosmic Aesthetic",
  "Mystical Art",
  "AstroArt Designs",
  "AstroArt Branch",
  "Archana's AstroArt Branch",
  "AstroArt Git",
  "Astrology Development",
  "AstroArt Deployment",
  "AstroArt Features",
  "AstroArt Code",
  "AstroApp",
  "AstroArt UI",
  "AstroArt Repo",
  "Archana-AstroArt Branding",
  "AstroArt Project",
  "Archana AstroArt UI",
  "AstroArt Cosmic Designs",
  "Archana Astrology",
  "AstroArt Development",
  "Astrology Features",
  "Archana Cosmic Branding",
  "Astrology Art Content",
  "AstroArt Personal Blog",
  "Mindfulness",
  "Personal Growth",
  "Astrology Insights",
  "AstroArt Tips",
  "Astrology Techniques",
  "AstroArt Tutorials",
  "Astrology Guides",
  "AstroArt Inspiration",
  "Astrology Predictions",
  "AstroArt Trends",
  "Astrology Innovations",
  "AstroArt Community",
  "Astrology Workshops",
  "AstroArt Events",
  "Astrology Courses",
  "AstroArt Learning",
  "Astrology Resources",
  "AstroArt Tools",
  "Astrology Software",
  "AstroArt Platforms",
  "Astrology Networks",
  "AstroArt Collaboration",
  "Astrology Partnerships",
  "AstroArt Ventures",
  "Astrology Startups",
  "AstroArt Entrepreneurs",
  "Astrology Business",
  "AstroArt Marketing",
  "Astrology Advertising",
  "AstroArt Promotion",
  "Astrology Outreach",
  "AstroArt Engagement",
  "Astrology Influence",
  "AstroArt Impact",
  "Astrology Reach",
  "AstroArt Visibility",
  "Astrology Presence",
  "AstroArt Branding",
  "Astrology Identity",
  "AstroArt Recognition",
  "Astrology Reputation",
  "AstroArt Authority",
  "Astrology Expertise",
  "AstroArt Knowledge",
  "Astrology Wisdom",
  "AstroArt Insights",
  "Astrology Analysis",
  "AstroArt Research",
  "Astrology Studies",
  "AstroArt Findings",
  "Astrology Discoveries",
  "AstroArt Exploration",
  "Astrology Adventures",
  "AstroArt Journeys",
  "Astrology Travels",
  "AstroArt Expeditions",
  "Astrology Quests",
  "AstroArt Missions",
  "Astrology Pilgrimages",
  "AstroArt Odysseys",
  "Astrology Voyages",
  "AstroArt Excursions",
  "Astrology Trips",
  "AstroArt Tours",
  "Astrology Safaris",
  "AstroArt Expeditions",
  "Astrology Treks",
  "AstroArt Hikes",
  "Astrology Walks",
  "AstroArt Strolls",
  "Astrology Rambles",
  "AstroArt Meanders",
  "Astrology Roams",
  "AstroArt Wanders",
  "Astrology Drifts",
  "AstroArt Saunters",
  "Astrology Ambles",
  "AstroArt Jaunts",
  "Astrology Outings",
  "AstroArt Excursions",
  "Astrology Journeys",
  "AstroArt Adventures",
  "Astrology Expeditions",
  "AstroArt Pilgrimages",
  "Astrology Quests",
  "AstroArt Missions",
  "Astrology Odysseys",
  "AstroArt Voyages",
  "Astrology Travels",
  "AstroArt Trips",
  "Astrology Tours",
  "AstroArt Safaris",
  "Astrology Treks",
  "AstroArt Hikes",
  "Astrology Walks",
  "AstroArt Strolls",
  "Astrology Rambles",
  "AstroArt Meanders",
  "Astrology Roams",
  "AstroArt Wanders",
  "Astrology Drifts",
  "AstroArt Saunters",
  "Astrology Ambles",
  "AstroArt Jaunts",
  "Astrology Outings",
];